# Generated by Django 3.2.8 on 2021-11-02 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.course')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_section_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_section_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('html5', 'HTML5'), ('video_file', 'Video File'), ('google_drive', 'Google Drive'), ('document', 'Document'), ('image_file', 'Image File'), ('iframe_embed', 'Iframe Embed')], default='youtube', max_length=30)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons/')),
                ('duration', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('is_free', models.BooleanField(default=False, help_text='Do you want to keep it free as a preview video?', verbose_name='Make as free lesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='courses.course')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_lesson_createdby', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_lessions', to='courses.section')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_lesson_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
