# Generated by Django 3.2.8 on 2021-11-02 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=100)),
                ('discount_percentage', models.IntegerField(default=0, help_text='The Discount range is 0 to 100.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('starting_date', models.DateTimeField(null=True)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
