# Generated by Django 3.2.8 on 2021-11-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
