# Generated by Django 3.2.8 on 2021-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_alter_coupon_starting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('symbol', models.ImageField(upload_to='currencies/')),
                ('paypal_supported', models.BooleanField(default=True)),
                ('stripe_supported', models.BooleanField(default=True)),
            ],
        ),
    ]
