# Generated by Django 3.2.8 on 2021-11-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='detail',
            new_name='message',
        ),
    ]
