# Generated by Django 3.2.8 on 2021-11-05 07:03

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_note',
            field=models.CharField(default='This website uses cookie to personalize content and analyse\n         in order to offer you a better exprerience.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_policy',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookies_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(default='www.facebook.com/lsm'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(default='www.linkedin.com/lsm'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recaptcha_secretkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recaptcha_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recaptcha_sitekey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recaptcha_version',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='refound_policy',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(default='www.twitter.com/lsm'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
