# Generated by Django 3.2.8 on 2021-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_auto_20211105_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['currency']},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.FloatField(null=True, verbose_name='Currency Exchange Rate'),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Currency Active?'),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Currency Symbol'),
        ),
    ]
