# Generated by Django 3.2.8 on 2021-11-13 13:45

from django.db import migrations, models
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0013_auto_20211113_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_default_currency',
            field=models.BooleanField(default=False, validators=[utilities.models.system_default_currency], verbose_name='Is System default currency?'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=150, unique=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Currency Active?'),
        ),
    ]
