# Generated by Django 3.2.8 on 2021-11-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0014_auto_20211113_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendSetting',
        ),
    ]
