# Generated by Django 3.2.8 on 2021-11-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0017_auto_20211113_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smtpsettings',
            old_name='protocaol',
            new_name='protocol',
        ),
    ]
