# Generated by Django 3.2.8 on 2021-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0018_rename_protocaol_smtpsettings_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_active', models.BooleanField(default=False, null=True)),
                ('facebook_api_id', models.CharField(max_length=255, null=True)),
                ('facebook_api_secret', models.CharField(max_length=255, null=True)),
                ('youtube_active', models.BooleanField(default=False, null=True)),
                ('youtube_api_key', models.CharField(max_length=255, null=True)),
                ('youtube_restrict_key', models.CharField(max_length=255, null=True)),
                ('twitter_active', models.BooleanField(default=False, null=True)),
                ('twitter_api_key', models.CharField(max_length=255, null=True)),
                ('twitter_restrict_key', models.CharField(max_length=255, null=True)),
                ('vimeo_active', models.BooleanField(default=False, null=True)),
                ('vimeo_api_key', models.CharField(max_length=255, null=True)),
                ('vimeo_restrict_key', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
